# Generated by Django 5.1.7 on 2025-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="Name",
            field=models.CharField(default="StudentName", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="RollNumber",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student",
            name="CityName",
            field=models.CharField(default="StudentCityName", max_length=100),
        ),
    ]
